version: '3.1'

services:
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USERNAME: postgres
            POSTGRES_DB: piikki_db
            POSTGRES_PASSWORD: example
            HOST: db
    test-db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USERNAME: postgres
            POSTGRES_DB: test-db
            POSTGRES_PASSWORD: test
            HOST: test-db

    backend:
        build: ./backend
        ports:
            - 3000:3000

    frontend:
        build: ./frontend
        ports:
            - 4173:4173
        depends_on:
            - backend
        environment:
            DOCKER: true