services:
    db:
        image: postgres
        restart: always
        container_name: tabapp-db
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            HOST: db
        depends_on:
            - redis
    test-db:
        image: postgres
        restart: always
        container_name: tabapp-test-db
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        depends_on:
            - redis

    backend:
        build: ./backend
        restart: always
        container_name: tabapp-backend
        ports:
            - 3000:3000
        environment:
            NODE_ENV: production
            POSTGRES_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
            REDIS_URL: redis://redis:6379

    frontend:
        build: ./frontend
        restart: always
        container_name: tabapp-frontend
        ports:
            - 4173:4173
        expose:
            - "4173"
        depends_on:
            - backend
        environment:
            DOCKER: true

    redis:
        image: redis:latest
        restart: always
        container_name: tabapp-redis
        ports:
            - 6379:6379

    caddy:
        image: caddy:latest
        container_name: tabapp-caddy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
        depends_on:
            - frontend
